# Generated by Django 4.2.30 on 2026-07-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(blank=True, help_text='e.g. Python, Django, SQLite', max_length=300, null=True),
        ),
    ]
