# Generated by Django 4.2.30 on 2026-07-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showcase', '0003_alter_personalinfo_address_alter_project_tech_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
